[node.websocket]
    address = "::ffff:0.0.0.0"
    enable = true
    port = 17078

[rpc]
    enable = true
    enable_sign_hash = true

[node]
    work_threads = 1
    enable_voting = true
    peering_port = 17075
    preconfigured_peers = []
    allow_local_peers = true
    #bandwidth_limit = 100000
    #active_elections_size = 5000

[node.block_processor]
    max_peer_queue = 256
    max_system_queue = 512000

#[node.message_processor]
#	max_queue = 4
