[node.websocket]
address = "::ffff:0.0.0.0"
enable = true
port = 17078

[rpc]
enable = true
enable_sign_hash = true

[node]
work_threads = 1
enable_voting = true
peering_port = 17075
preconfigured_peers = []
allow_local_peers = true

[node.block_processor]
max_peer_queue = 256000
max_system_queue = 512000