[node.websocket]
    address = "::ffff:0.0.0.0"
    enable = true
    port = 17078

[rpc]
    enable = true
    enable_sign_hash = true

[node]
    work_threads = 1
    enable_voting = true
    peering_port = 17075
    preconfigured_peers = []
    allow_local_peers = true
    active_elections_size = 500
     max_peers_per_ip = 99
    max_peers_per_subnetwork = 99

[node.active_elections]
	size = 500