confirmation_timeout_seconds = 10
threshold = 219000
legit_blocks_path = "_resources/blocks/5n4pr_bucket_rounds_2-3_1000-2000.json"
rpc_endpoints = [
  "http://127.0.0.1:45101",
  "http://127.0.0.1:45102",
  "http://127.0.0.1:45103",
  "http://127.0.0.1:45104",
]
